# FROM node
FROM node:20.9.0-alpine3.18

WORKDIR /v2

# Dosyaları al ve wokdir içine gönder
COPY . .

RUN npm i -g yarn
RUN yarn

CMD ["npm", "start"]
EXPOSE 5175



# --------------------------------
# $ cd /v2_my
# $ docker build -t myperformans .
# $ docker run -p 5173:5173 --name myperformans myperformans
# $ docker run -d -p 5173:5173 --name myperformans myperformans
# $ docker run -d -p 80:5173 --name myperformans bonnadijital/myperformans
# Browser: http://localhost:5173

# docker stop <container_id_or_name>