# Base image
FROM node:latest

# Çalışma dizini oluşturma
WORKDIR /v2

# Bağımlılıkları kopyalama ve yükleme
COPY package.json yarn.lock ./
# RUN yarn config set registry https://registry.npmjs.org/
# RUN yarn cache clean && yarn install

# Uygulama dosyalarını kopyalama
COPY . .

# Uygulamayı başlatma
CMD ["yarn", "start"]